//Powered By Kyzryzz * kyzryzz.t.me
//Powered By Kyzryzz * kyzryzz.t.me
let handler = async (m, { conn, usedPrefix, command }) => {
		
			await conn.sendMessage(m.chat, { video: { url: dir[Math.floor(Math.random() * dir.length)] }, caption: `_Random JJ Anime_` }, { quoted: m })
	}

handler.help = ['jjanime']
handler.tags = ['anime','premium']
handler.command = /^(jjanime)$/i
handler.limit = true
handler.premium = true
handler.register = true

module.exports = handler;

const dir = [
'https://pomf2.lain.la/f/kmbh9nxj.mp4',
'https://pomf2.lain.la/f/515034me.mp4',
'https://pomf2.lain.la/f/6zfe4shg.mp4',
'https://pomf2.lain.la/f/go0b7noz.mp4',
'https://pomf2.lain.la/f/0jud5hap.mp4',
'https://pomf2.lain.la/f/8rsnlrdp.mp4',
'https://pomf2.lain.la/f/gz11tran.mp4',
'https://pomf2.lain.la/f/ibjhv8f4.jpg',
'https://pomf2.lain.la/f/2bosmn9w.mp4',
'https://pomf2.lain.la/f/i0amfclw.mp4',
'https://pomf2.lain.la/f/djamigq1.mp4',
'https://pomf2.lain.la/f/b95acwmd.mp4',
'https://pomf2.lain.la/f/y4hoe7td.mp4',
'https://www.mediafire.com/file/v0mcysuzztr3uvd/1.mp4/file', 
'https://www.mediafire.com/file/nyeadgp7ruw40hv/2.mp4/file', 
'https://www.mediafire.com/file/a9xurgeoazs7r04/3.mp4/file', 
'https://www.mediafire.com/file/dcrh2uwvdi2egfk/4.mp4/file', 
'https://www.mediafire.com/file/1vexz9o0a055jx4/5.mp4/file', 
'https://www.mediafire.com/file/34kg7n94b5r4tbr/6.mp4/file', 
'https://www.mediafire.com/file/sfrww7ww32u8ofu/7.mp4/file', 
'https://www.mediafire.com/file/ncdgm0o43r0wm8b/8.mp4/file', 
'https://www.mediafire.com/file/svbolfcj01rij9o/9.mp4/file', 
'https://www.mediafire.com/file/3w5b5t3qqn37bj2/10.mp4/file', 
'https://www.mediafire.com/file/07dgk2ywzeooceh/11.mp4/file', 
'https://www.mediafire.com/file/uqrmf3tj79dpzuw/12.mp4/file', 
'https://www.mediafire.com/file/1vti0r2swfotena/13.mp4/file', 
'https://www.mediafire.com/file/4ac9wlfiqu4mbak/14.mp4/file', 
'https://www.mediafire.com/file/snss4pxqxvxqppl/15.mp4/file', 
'https://www.mediafire.com/file/iixzkzyf99lq4gh/16.mp4/file', 
'https://www.mediafire.com/file/xmtkog706fdebty/17.mp4/file', 
'https://www.mediafire.com/file/62k6sn0ixiu3vd7/18.mp4/file', 
'https://www.mediafire.com/file/6nht4t04vtyqbka/19.mp4/file', 
'https://www.mediafire.com/file/urzjzki8m3byztx/20.mp4/file', 
'https://www.mediafire.com/file/ah4y4efj3kbkc11/21.mp4/file', 
'https://www.mediafire.com/file/cteqbh2lso9mdng/22.mp4/file', 
'https://www.mediafire.com/file/7qh2ofhdlbrdj0n/23.mp4/file', 
'https://www.mediafire.com/file/dd9ta0010daemgb/24.mp4/file', 
'https://www.mediafire.com/file/lcnt4sw0tyjwjwr/25.mp4/file', 
'https://www.mediafire.com/file/a5l3nwxtu5kt3nm/26.mp4/file', 
'https://www.mediafire.com/file/m107c2oqz6zfvk4/1.mp4/file', 
'https://www.mediafire.com/file/fv2mw8x2wf0q3ed/2.mp4/file', 
'https://www.mediafire.com/file/l4b06jhvu99zzbe/3.mp4/file', 
'https://www.mediafire.com/file/xywoh52tnog2rei/4.mp4/file', 
'https://www.mediafire.com/file/nsn1gvby2ezead9/5.mp4/file', 
'https://www.mediafire.com/file/oyauxsuou5122z3/6.mp4/file', 
'https://www.mediafire.com/file/wadn3hggh7i8c8s/7.mp4/file', 
'https://www.mediafire.com/file/haclfjfjrr41x15/8.mp4/file', 
'https://www.mediafire.com/file/7u2f2aoovhx5rq0/9.mp4/file', 
'https://www.mediafire.com/file/vh3rcb345v41san/10.mp4/file', 
'https://www.mediafire.com/file/61ysqfilbb11gdr/11.mp4/file', 
'https://www.mediafire.com/file/jm7r15vxro9onb9/12.mp4/file', 
'https://www.mediafire.com/file/f70o57bbek5egg6/13.mp4/file', 
'https://www.mediafire.com/file/8pjoyvk9gtbd4ox/14.mp4/file', 
'https://www.mediafire.com/file/t5pdiwjucjzhl8b/15.mp4/file', 
'https://www.mediafire.com/file/b8m9z6r7rud5x4v/16.mp4/file', 
'https://www.mediafire.com/file/ignf02xe0d21snb/17.mp4/file', 
'https://www.mediafire.com/file/a4k0wzh2uovitjz/18.mp4/file', 
'https://www.mediafire.com/file/cy30pn9bajndo3o/19.mp4/file', 
'https://www.mediafire.com/file/8g7b6s36tc4gm6r/20.mp4/file', 
'https://www.mediafire.com/file/q5x5wk6vtebrymk/21.mp4/file', 
'https://www.mediafire.com/file/7pvz1vi3g2cl8qn/22.mp4/file', 
'https://www.mediafire.com/file/6xin5was2bl4uwd/23.mp4/file', 
'https://www.mediafire.com/file/2pd4o7zjur69diq/24.mp4/file', 
'https://www.mediafire.com/file/vjlhgfz9jfycign/25.mp4/file', 
'https://www.mediafire.com/file/yskvimf0bn4x3ge/26.mp4/file', 
'https://www.mediafire.com/file/d5fviis1gmkj4cz/27.mp4/file', 
'https://www.mediafire.com/file/qxhptj8wz6bsjrq/1g.mp4/file', 
'https://www.mediafire.com/file/acxujcozd7m12s1/2g.mp4/file', 
'https://www.mediafire.com/file/jj5ti4bfo1ak9wp/3g.mp4/file', 
'https://www.mediafire.com/file/twtnu9bxdq7q16n/4g.mp4/file', 
'https://www.mediafire.com/file/tfi1dlxeh4whlnl/5g.mp4/file', 
'https://www.mediafire.com/file/o57q5rdi9cv7m9r/6g.mp4/file', 
'https://www.mediafire.com/file/dl30z4hx7ixvgp0/7g.mp4/file', 
'https://www.mediafire.com/file/x5byoatyd0zi474/8g.mp4/file', 
'https://www.mediafire.com/file/lnn7auabovq884k/9g.mp4/file', 
'https://www.mediafire.com/file/r7omk0mb6oegtoc/10g.mp4/file', 
'https://www.mediafire.com/file/lou4idrm1p2buax/11g.mp4/file', 
'https://www.mediafire.com/file/1bn0eo8m3xab6dv/12g.mp4/file', 
'https://www.mediafire.com/file/ucknyz3rwahel1r/13g.mp4/file', 
'https://www.mediafire.com/file/2h0xarp01f694xf/14g.mp4/file', 
'https://www.mediafire.com/file/rzu9cxxzku4y89w/15g.mp4/file', 
'https://www.mediafire.com/file/mi5q38lc5oudlal/16g.mp4/file', 
'https://www.mediafire.com/file/eh2m8skd3nqr375/17g.mp4/file', 
'https://www.mediafire.com/file/hgvu9rjfbytpseb/18g.mp4/file', 
'https://www.mediafire.com/file/ba9jk8p36zlmqbt/19g.mp4/file', 
'https://www.mediafire.com/file/poq203kc89msltp/20g.mp4/file', 
'https://www.mediafire.com/file/416myzm67sbjxkk/21g.mp4/file', 
'https://www.mediafire.com/file/g6uh6w65nremiyg/22g.mp4/file', 
'https://www.mediafire.com/file/0el8imcdg4cieof/23g.mp4/file', 
'https://www.mediafire.com/file/0lj1tyw1h0kkfdp/24g.mp4/file', 
'https://www.mediafire.com/file/8ox85e5z3u7t5zw/25g.mp4/file', 
'https://www.mediafire.com/file/ybqbon846gmmznx/26g.mp4/file', 
'https://www.mediafire.com/file/insqyrzn4k35ccc/27g.mp4/file', 
'https://www.mediafire.com/file/3yvgpmh1tx9zja3/28g.mp4/file', 
'https://www.mediafire.com/file/8uhoc38bb4yq1jm/29g.mp4/file', 
'https://www.mediafire.com/file/v1exg9vjhbv4xb5/30g.mp4/file', 
]